### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by jaan143** [Phoenix124/scribd-downloader#12]
hello after installed everything i am getting these errors
i have created text file but i dont know in which directory i should save this scribd_credentials.txt
kindly help me to solve it 
PS C:\Users\vicky> scribdl -c scribd_credentials.txt https://www.scribd.com/audiobook/359295794/Principles-Life-and-Work
Fontconfig error: Cannot load default config file
C:\Users\vicky\AppData\Local\Programs\Python\Python36\lib\site-packages\weasyprint\fonts.py:217: UserWarning: @font-face not supported: FontConfig cannot load default config file
  '@font-face not supported: '
C:\Users\vicky\AppData\Local\Programs\Python\Python36\lib\site-packages\weasyprint\fonts.py:455: UserWarning: Expect ugly output with font-size: 0
  warnings.warn('Expect ugly output with font-size: 0')
C:\Users\vicky\AppData\Local\Programs\Python\Python36\lib\site-packages\weasyprint\document.py:36: UserWarning: There are known rendering problems and missing features with cairo < 1.15.4. WeasyPrint may work with older versions, but please read the note about the needed cairo version on the "Install" page of the documentation before reporting bugs. http://weasyprint.readthedocs.io/en/latest/install.html
  'There are known rendering problems and missing features with '
Traceback (most recent call last):
  File "C:\Users\vicky\AppData\Local\Programs\Python\Python36\Scripts\scribdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')())
  File "C:\Users\vicky\AppData\Local\Programs\Python\Python36\lib\site-packages\scribd_downloader-1.3.1-py3.6.egg\scribdl\command_line.py", line 51, in _command_line
  File "C:\Users\vicky\AppData\Local\Programs\Python\Python36\lib\site-packages\scribd_downloader-1.3.1-py3.6.egg\scribdl\authorize.py", line 27, in set_credentials
FileNotFoundError: [Errno 2] No such file or directory: 'scribd_credentials.txt'

**Comment by Geremia** [comment]
@jaan143 Do you have a file named `scribd_credentials.txt` in your `C:\Users\vicky` directory?

**Comment by jaan143** [comment]
@Geremia is it working fine in your computer ?

**Comment by Geremia** [comment]
@jaan143 Please see [this comment](https://github.com/Phoenix124/scribd-downloader/issues/33#issuecomment-955091341).

**Comment by mrtztg** [comment]
You can use this script to audiobooks:
https://github.com/mrtztg/scribd_dl

**Comment by Phoenix124** [comment]
WeasyPrint and its system libraries (cairo, pango) are now imported only when you pass `-p/--pdf`. Downloads without `--pdf` no longer need them (currently in the `fix` branch, will land in `master` with the next merge).
