### ISSUE TITLE
can't get this to work

### ISSUE THREAD

**Issue by johndpope** [Phoenix124/scribd-downloader#16]
scribdl -i -c cred.txt https://www.scribd.com/book/272741038/Michael-Buble-Let-It-Snow --pdf
(base) ➜  scribd-downloader git:(master) ✗ scribdl -i -c cred.txt https://www.scribd.com/book/272741038/Michael-Buble-Let-It-Snow --pdf

Converting to Michael_Bublé_-_Let_It_Snow.pdf..
Traceback (most recent call last):
  File "/Users/admin/miniconda3/bin/scribdl", line 11, in <module>
    load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')()
  File "/Users/admin/miniconda3/lib/python3.7/site-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/command_line.py", line 57, in _command_line
  File "/Users/admin/miniconda3/lib/python3.7/site-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/pdf_converter.py", line 29, in to_pdf
  File "/Users/admin/miniconda3/lib/python3.7/site-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/pdf_converter.py", line 47, in _images_to_pdf
  File "/Users/admin/miniconda3/lib/python3.7/site-packages/img2pdf-0.4.0-py3.7.egg/img2pdf.py", line 2084, in convert
  File "/Users/admin/miniconda3/lib/python3.7/site-packages/img2pdf-0.4.0-py3.7.egg/img2pdf.py", line 955, in tostring
  File "/Users/admin/miniconda3/lib/python3.7/site-packages/img2pdf-0.4.0-py3.7.egg/img2pdf.py", line 1049, in tostream
IndexError: Accessing nonexistent PDF page number
(base) ➜  scribd-downloader git:(master) ✗ l

**Comment by Phoenix124** [comment]
This is a Scribd book URL. Scribd books now redirect to Everand, which isn't supported (see #50). The tool now stops with a clear error instead of crashing (currently in the `fix` branch, will land in `master` with the next merge).
