### ISSUE TITLE
this error...

### ISSUE THREAD

**Issue by VikasRana** [Phoenix124/scribd-downloader#19]
Traceback (most recent call last):
  File "C:\Python37\Scripts\scribdl-script.py", line 11, in <module>
    load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')()
  File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "C:\Python37\lib\site-packages\pkg_resources\__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python37\scribdl\__init__.py", line 3, in <module>
    from .downloader import Downloader
  File "C:\Python37\scribdl\downloader.py", line 9, in <module>
    from .pdf_converter import ConvertToPDF
  File "C:\Python37\scribdl\pdf_converter.py", line 1, in <module>
    from md2pdf.core import md2pdf
  File "C:\Python37\lib\site-packages\md2pdf-0.4-py3.7.egg\md2pdf\__init__.py", line 3, in <module>
    from md2pdf.core import (
  File "C:\Python37\lib\site-packages\md2pdf-0.4-py3.7.egg\md2pdf\core.py", line 3, in <module>
    from weasyprint import HTML, CSS
  File "C:\Python37\lib\site-packages\weasyprint-51-py3.7.egg\weasyprint\__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "C:\Python37\lib\site-packages\weasyprint-51-py3.7.egg\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "C:\Python37\lib\site-packages\weasyprint-51-py3.7.egg\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "C:\Python37\lib\site-packages\weasyprint-51-py3.7.egg\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "C:\Python37\lib\site-packages\cairocffi-1.1.0-py3.7.egg\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "C:\Python37\lib\site-packages\cairocffi-1.1.0-py3.7.egg\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e

**Comment by Phoenix124** [comment]
WeasyPrint and its system libraries (cairo, pango) are now imported only when you pass `-p/--pdf`. Downloads without `--pdf` no longer need them (currently in the `fix` branch, will land in `master` with the next merge).
