### ISSUE TITLE
Audiobook's Error

### ISSUE THREAD

**Issue by TnT420** [Phoenix124/scribd-downloader#26]
My Command

scribdl -c scribd_credentials.txt "https://www.scribd.com/audiobook/xxxxx/abc"

Error:

Traceback (most recent call last):
  File "/usr/local/bin/scribdl", line 33, in <module>
    sys.exit(load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')())
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/command_line.py", line 54, in _command_line
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/downloader.py", line 39, in download
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/downloader.py", line 84, in _download_audiobook
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/content/audiobook.py", line 216, in playlist
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/content/audiobook.py", line 286, in make_playlist
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/content/audiobook.py", line 205, in premium_cookies
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/content/audiobook.py", line 177, in license_id
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/content/audiobook.py", line 225, in _get_license_id
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/content/audiobook.py", line 167, in license_url
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/content/audiobook.py", line 158, in author_id
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/content/audiobook.py", line 106, in audiobook_keys
  File "/usr/local/lib/python3.7/dist-packages/scribd_downloader-1.3.1-py3.7.egg/scribdl/content/audiobook.py", line 247, in _scrape_audiobook_page
TypeError: 'NoneType' object is not subscriptable

**Comment by mrtztg** [comment]
Use this script for download audiobooks: 
https://github.com/mrtztg/scribd_dl

I developed it today. Use and give feedback.

**Comment by TnT420** [comment]
> 
> 
> Use this script for download audiobooks:
> https://github.com/mrtztg/scribd_dl
> 
> I developed it today. Use and give feedback.

It's working perfectly, appreciate it!

**Comment by chimeforest** [comment]
I'm getting this error for audiobooks too.
And a similar one for documents.

I tried mrtztg's script today with mixed results.

**Comment by Phoenix124** [comment]
Scribd has moved books and audiobooks to Everand. Their Scribd URLs now redirect there, and the old endpoints this tool used return 404/410. The tool now stops with a clear "Scribd redirected to Everand" error (currently in the `fix` branch, will land in `master` with the next merge). Everand support is tracked in #50, so I'm closing this one as a duplicate.
