### ISSUE TITLE
Setup gone wrong!?

### ISSUE THREAD

**Issue by dinhhung893** [Phoenix124/scribd-downloader#32]
I got this error when trying to run script 
![image](https://user-images.githubusercontent.com/40659635/125207350-f5755f00-e2b5-11eb-9264-7a8be449cf96.png)
Any solution, please help!!

**Comment by ElegantPercentage** [comment]
```
pip install --upgrade pip
pip install --upgrade Pillow
pip install scribd-downloader
```

Try the above solution for your windows machine. The script isn't working however. Because it's unable to login.

**Comment by dinhhung893** [comment]
> ```
> pip install --upgrade pip
> pip install --upgrade Pillow
> pip install scribd-downloader
> ```
> 
> Try the above solution for your windows machine. The script isn't working however. Because it's unable to login.

Oh, okay. So do you know any downloader can get book from Scribd? Please let me know!!

**Comment by Phoenix124** [comment]
@dinhhung893 try `scribdl -p  https://www.scribd.com/read/189087235/Confessions-of-a-Casting-Director-Help-Actors-Land-Any-Role-with-Secrets-from-Inside-the-Audition-Room`

**Comment by Gutem** [comment]
I'm getting:

```python
$ pip3 install scribd-downloader
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scribd-downloader in /usr/local/lib/python3.10/dist-packages/scribd_downloader-1.3.1-py3.10.egg (1.3.1)
Requirement already satisfied: requests>=2.19.1 in /home/gutem/.local/lib/python3.10/site-packages (from scribd-downloader) (2.28.1)
Requirement already satisfied: BeautifulSoup4>=4.6.3 in /home/gutem/.local/lib/python3.10/site-packages (from scribd-downloader) (4.11.1)
Collecting img2pdf>=0.3.1
  Downloading img2pdf-0.4.4.tar.gz (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting md2pdf>=0.4
  Downloading md2pdf-0.6.tar.gz (6.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-7ydixpn2/md2pdf_369e92c852be49eeb88b3d471d25256b/setup.py", line 7, in <module>
          import md2pdf
        File "/tmp/pip-install-7ydixpn2/md2pdf_369e92c852be49eeb88b3d471d25256b/md2pdf/__init__.py", line 8, in <module>
          from md2pdf.core import md2pdf  # noqa
        File "/tmp/pip-install-7ydixpn2/md2pdf_369e92c852be49eeb88b3d471d25256b/md2pdf/core.py", line 4, in <module>
          from markdown2 import markdown, markdown_path
      ModuleNotFoundError: No module named 'markdown2'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
on: 
```
$ uname -a
Linux beast 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Phoenix124** [comment]
Old installs from PyPI (1.3.1) are outdated, and the package isn't on PyPI anymore. Reinstall from GitHub with `pip install git+https://github.com/Phoenix124/scribd-downloader.git`. Note that the Scribd book URL used here now redirects to Everand, which isn't supported (see #50). Documents still work.
