### ISSUE TITLE
Audiobook download issue

### ISSUE THREAD

**Issue by hawkeye2nd** [Phoenix124/scribd-downloader#40]
Getting this error:
`Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\Scripts\scribdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')())
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\command_line.py", line 54, in _command_line
    downloaded_content = scribd_link.download(is_image_document=images)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\downloader.py", line 39, in download
    content = self._download_audiobook()
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\downloader.py", line 84, in _download_audiobook
    playlist = audiobook.playlist
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\content\audiobook.py", line 216, in playlist
    self._playlist = Playlist(self.title, self.make_playlist())
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\content\audiobook.py", line 286, in make_playlist
    if self.premium_cookies:
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\content\audiobook.py", line 205, in premium_cookies
    premium_cookies = bool(self.license_id)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\content\audiobook.py", line 177, in license_id
    self._license_id = self._get_license_id()
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\content\audiobook.py", line 225, in _get_license_id
    response = requests.get(self.license_url, headers=self.headers)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\content\audiobook.py", line 167, in license_url
    return "https://api.findawayworld.com/v4/accounts/scribd-{0}/audiobooks/{1}".format(self.author_id, self.book_id)
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\content\audiobook.py", line 158, in author_id
    audiobook = self.audiobook_keys
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\content\audiobook.py", line 106, in audiobook_keys
    audiobook_keys = self._scrape_audiobook_page()
  File "C:\Users\A\AppData\Local\Programs\Python\Python310\lib\site-packages\scribdl\content\audiobook.py", line 247, in _scrape_audiobook_page
    text = json.loads(div_tag["data-push_state"])
TypeError: 'NoneType' object is not subscriptable`

**Comment by mrtztg** [comment]
You can use this script:
https://github.com/mrtztg/scribd_dl

**Comment by Phoenix124** [comment]
Scribd has moved books and audiobooks to Everand. Their Scribd URLs now redirect there, and the old endpoints this tool used return 404/410. The tool now stops with a clear "Scribd redirected to Everand" error (currently in the `fix` branch, will land in `master` with the next merge). Everand support is tracked in #50, so I'm closing this one as a duplicate.
