### ISSUE TITLE
Credentials issue

### ISSUE THREAD

**Issue by olafx** [Phoenix124/scribd-downloader#41]
Credentials aren't working. Not sure why, error gives no hints. The credentials file exists (it gives a different error when I remove it) and doesn't seem to be a permissions issue, doesn't work with sudo either.

```
(main) swift@taylor ~ % scribdl -c scribd_credentials.txt https://www.scribd.com/read/332994411/The-Three-Body-Problem
/Users/swift/venv/main/lib/python3.9/site-packages/cryptography/hazmat/backends/openssl/x509.py:15: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/swift/venv/main/bin/scribdl", line 33, in <module>
    sys.exit(load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')())
  File "/Users/swift/venv/main/lib/python3.9/site-packages/scribd_downloader-1.3.1-py3.9.egg/scribdl/command_line.py", line 51, in _command_line
  File "/Users/swift/venv/main/lib/python3.9/site-packages/scribd_downloader-1.3.1-py3.9.egg/scribdl/authorize.py", line 55, in set_credentials
scribdl.exceptions.ScribdFetchError: Login error: An error occurred please try again.
```

**Comment by SigmaDuck894** [comment]
I have also run into this issue. It seems like Scribd modify their site for this to not work. Hope someone can fix this.

**Comment by flagmaggot** [comment]
Well you can enter your own _session_expire and _scribd_session values but even then it only downloads the first page.

**Comment by matthew-clark3** [comment]
Same issue. Use of the .egg file makes  creating a work around frustrating.

**Comment by dylb0t** [comment]
> Same issue. Use of the .egg file makes creating a work around frustrating.

If you use VSCode, create a launch.json and a settings.json in the .vscode folder. This will allow you to debug. The egg is used only if you run the setup.py to install.

settings.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            "python.analysis.extraPaths": [
                "${workspaceFolder}/scribdl/,${workspaceFolder}/scribdl_downloader,${workspaceFolder}/build"
            ]
        }
    ]
}
`
launch.json (fill credentials.txt with your login credentials, in the root. Also put an audiobook you have access to.
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: scribdl commandline Module",
            "type": "python",
            "request": "launch",
            "module": "scribdl.command_line",
            "justMyCode": true,
            "args": [
                "https://www.scribd.com/audiobook/237606860/100-Ways-to-Motivate-Yourself-Change-Your-Life-Forever",
                "-c",
                "credentials.txt"
            ],
            "env": {
                "PYTHONPATH": "${workspaceFolder}/scribdl"
            },
            "autoReload": {
                "enable": true
            }
        }`

**Comment by dylb0t** [comment]
This is where we get to in the debug:
`{"form_name":null,"errors":[{"input_name":"login_or_email","msg":"An error occurred please try again."}]}`
it is in authorize.py, and right when you get the response on around line 43. I checked the values in the SCRIBD_LOGIN_DATA and they are correct. 
This is as far as I have made it so far, so probably need somebody with soup knowlege to help here.

**Comment by theoriginalbxhx** [comment]
Has there been any headway made with this. I'm having the same issue. 

`$ scribdl -c scribd_credentials.txt https://www.scribd.com/read/235007189/A-Basic-Guide-to-Interpreting-the-Bible-Playing-by-the-Rules
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/scribdl", line 8, in <module>
    sys.exit(_command_line())
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scribdl/command_line.py", line 51, in _command_line
    authorize.set_credentials(credentials_file)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scribdl/authorize.py", line 55, in set_credentials
    raise exceptions.ScribdFetchError("Login error: " + errors[0]["msg"])
scribdl.exceptions.ScribdFetchError: Login error: An error occurred please try again.`

**Comment by Phoenix124** [comment]
Scribd changed its login flow, so password login via `-c` fails with "An error occurred please try again". As a workaround there's a new `--cookies FILE` option (currently in the `fix` branch, will land in `master` with the next merge): put `_scribd_session=...` and `_scribd_expire=...` (copied from a logged-in browser) in the file, one per line. Note that books and audiobooks have moved to Everand and aren't supported anymore (see #50).
