### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\ue000'

### ISSUE THREAD

**Issue by 3xploiton3** [Phoenix124/scribd-downloader#45]
error parsing process document scribd 

reference: https://www.scribd.com/document/632385602/PIS-Coco-Charcoal-Briquette-1-Page-Presentation

![image](https://github.com/Phoenix124/scribd-downloader/assets/19517680/f0b7087f-399a-4938-98c9-77b35add8aad)

> Social and economic benefits

Traceback (most recent call last):
  File "C:\Python311\Scripts\scribdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\scribd_downloader-1.3.1-py3.11.egg\scribdl\command_line.py", line 54, in _command_line
  File "C:\Python311\Lib\site-packages\scribd_downloader-1.3.1-py3.11.egg\scribdl\downloader.py", line 51, in download
  File "C:\Python311\Lib\site-packages\scribd_downloader-1.3.1-py3.11.egg\scribdl\downloader.py", line 74, in _download_document
  File "C:\Python311\Lib\site-packages\scribd_downloader-1.3.1-py3.11.egg\scribdl\content\document.py", line 91, in download
  File "C:\Python311\Lib\site-packages\scribd_downloader-1.3.1-py3.11.egg\scribdl\content\document.py", line 99, in _text_extractor
  File "C:\Python311\Lib\site-packages\scribd_downloader-1.3.1-py3.11.egg\scribdl\content\document.py", line 124, in _save_text
  File "C:\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\ue000' in position 0: character maps to <undefined>

**Comment by Phoenix124** [comment]
Fixed (currently in the `fix` branch, will land in `master` with the next merge): text is written to files as UTF-8, and characters the Windows console can't show are replaced instead of crashing.
